img-name=pyint-bot
tag=snapshot
name=$(img-name)-$(tag)
registry=docker.hub.com
mem_limit=512M
cpu_limit=".5"
telekey="464758454:AAGICF84Ap9i2K7OVELAoSQ0rkjiGgEBpOs"
volume=pyint_bot_chats
runargs=--publish-all \
    --detach \
    --restart=always \
    --cpus=$(cpu_limit) \
    --memory=$(mem_limit) \
    -e TELEKEY=$(telekey)
    
#store_limit=512M
#--storage-opt size=$(store_limit) \ #can only use with xfs and similar filesystems
